### PR TITLE
Add LinearSymbolicComparator 

### PR DESCRIPTION
**Pull request by JunpengGao233**

### CODE REVIEW

**Comment by chriselrod** [comment]
Okay, I think this looks good.

Do you want to update for the changes I discussed here?
https://github.com/JuliaSIMD/LoopModels/pull/14#issuecomment-1200697952

If not, I can merge and do the update.

Main things are some functions disappeared (e.g. `view`), using `PtrVector<T>` and `PtrVector<const T>` instead of `llvm::MutableArrayRef<T>` and `llvm::ArrayRef<T>`, respectively, and supporting linear algebra.

There may be bugs and missing features, in which case one of us can add them.

**Comment by JunpengGao233** [comment]
> #14 (comment)

Hi Chris,

I try to merge it and modify the code, but I didn't make it. It seems to change a little much. If possible, could you help me update it a little? I am afraid I may mess it up.

**Comment by chriselrod** [comment]
> For example, why do we define a new struct for the transposed matrix?

In Julia, we have at least three structs for transposed matrices, `Transpose{T,Matrix,{T}}`, `Adjoint{T,Matrix{T}}`, and `PermutedDimsArray{T, 2, (2, 1), (2, 1), Matrix{T}}` ;).

The `Transpose` I added is like `Transpose{T,Matrix{T}}` in Julia.
It is a lazy wrapper.

If you assign `IntMatrix A{B.transpose()}`, `B.transpose()` will return the lazy-wrapper, which will then be converted to an `IntMatrix`, restoring the old behavior.

Much of the new functionality is lazy, creating new objects that represent the computations.
Like broadcasting is in Julia.
While `materialize` or `materialize!` get called in Julia based on syntax, i.e. where the `.`s were, in C++ the materialization happens when the lazy object is forced to convert to a non-lazy object, e.g. on assignment, or in theory on function calls.
But the function calls obviously wasn't working, given your errors.

That does mean you may have to be a little cautious to avoid doubling up on computation.

**Comment by JunpengGao233** [comment]
Thanks! I understand the design better!

**Pull request merged**
